//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SamWeb.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره پروژه سام.
        /// </summary>
        public static string AboutSam {
            get {
                return ResourceManager.GetString("AboutSam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمتن دربارهمت [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutSamExplanation {
            get {
                return ResourceManager.GetString("AboutSamExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه اطلاع رسانی مساجد.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سام.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string CellPhoneNumber {
            get {
                return ResourceManager.GetString("CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید و ادامه.
        /// </summary>
        public static string ConfirmAndContinue {
            get {
                return ResourceManager.GetString("ConfirmAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید و پرداخت.
        /// </summary>
        public static string ConfirmAndPay {
            get {
                return ResourceManager.GetString("ConfirmAndPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو شده.
        /// </summary>
        public static string ConsolationStatus_Canceled {
            get {
                return ResourceManager.GetString("ConsolationStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید شده.
        /// </summary>
        public static string ConsolationStatus_Confirmed {
            get {
                return ResourceManager.GetString("ConsolationStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش یافته.
        /// </summary>
        public static string ConsolationStatus_Displayed {
            get {
                return ResourceManager.GetString("ConsolationStatus_Displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر تأیید.
        /// </summary>
        public static string ConsolationStatus_Pending {
            get {
                return ResourceManager.GetString("ConsolationStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات شما.
        /// </summary>
        public static string CreateConsolationCustomerInfoStep {
            get {
                return ResourceManager.GetString("CreateConsolationCustomerInfoStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب مجلس ترحیم.
        /// </summary>
        public static string CreateConsolationObitSelectionStep {
            get {
                return ResourceManager.GetString("CreateConsolationObitSelectionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان عملیات.
        /// </summary>
        public static string CreateConsolationSuccessStep {
            get {
                return ResourceManager.GetString("CreateConsolationSuccessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای پیام تسلیت.
        /// </summary>
        public static string CreateConsolationTemplateInfoStep {
            get {
                return ResourceManager.GetString("CreateConsolationTemplateInfoStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب الگوی پیام تسلیت.
        /// </summary>
        public static string CreateConsolationTemplateSelectionStep {
            get {
                return ResourceManager.GetString("CreateConsolationTemplateSelectionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اَپ موبایل.
        /// </summary>
        public static string DownloadApp {
            get {
                return ResourceManager.GetString("DownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول شرکت آرت استون ایرانیان.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنمای استفاده.
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه است [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowToUseExplanation {
            get {
                return ResourceManager.GetString("HowToUseExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسجد.
        /// </summary>
        public static string Mosque {
            get {
                return ResourceManager.GetString("Mosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساجد عضو.
        /// </summary>
        public static string MosqueBrowser {
            get {
                return ResourceManager.GetString("MosqueBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراسم.
        /// </summary>
        public static string Obit {
            get {
                return ResourceManager.GetString("Obit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسمتی از نام مسجد.
        /// </summary>
        public static string PartOfMosqueName {
            get {
                return ResourceManager.GetString("PartOfMosqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت پرداخت.
        /// </summary>
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت ناموفق.
        /// </summary>
        public static string PaymentStatus_Failed {
            get {
                return ResourceManager.GetString("PaymentStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر پرداخت.
        /// </summary>
        public static string PaymentStatus_Pending {
            get {
                return ResourceManager.GetString("PaymentStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر تأیید نهایی.
        /// </summary>
        public static string PaymentStatus_Succeeded {
            get {
                return ResourceManager.GetString("PaymentStatus_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شده.
        /// </summary>
        public static string PaymentStatus_Verified {
            get {
                return ResourceManager.GetString("PaymentStatus_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        public static string PriceUnit {
            get {
                return ResourceManager.GetString("PriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت پیام تسلیت.
        /// </summary>
        public static string RegisterConsolation {
            get {
                return ResourceManager.GetString("RegisterConsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام تسلیت.
        /// </summary>
        public static string SendConsolation {
            get {
                return ResourceManager.GetString("SendConsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهگیری پیام.
        /// </summary>
        public static string TrackConsolation {
            get {
                return ResourceManager.GetString("TrackConsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رهگیری پیام.
        /// </summary>
        public static string TrackingNumber {
            get {
                return ResourceManager.GetString("TrackingNumber", resourceCulture);
            }
        }
    }
}
