//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamWeb.Mabnacard.TokenSpace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://token.ws.web.cnpg/", ConfigurationName="Mabnacard.TokenSpace.TokenService")]
    public interface TokenService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://token.ws.web.cnpg/TokenService/reservationRequest", ReplyAction="http://token.ws.web.cnpg/TokenService/reservationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SamWeb.Mabnacard.TokenSpace.reservationResponse reservation(SamWeb.Mabnacard.TokenSpace.reservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://token.ws.web.cnpg/TokenService/reservationRequest", ReplyAction="http://token.ws.web.cnpg/TokenService/reservationResponse")]
        System.Threading.Tasks.Task<SamWeb.Mabnacard.TokenSpace.reservationResponse> reservationAsync(SamWeb.Mabnacard.TokenSpace.reservationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://token.ws.web.cnpg/")]
    public partial class tokenDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aMOUNTField;
        
        private string cRNField;
        
        private string mIDField;
        
        private string rEFERALADRESSField;
        
        private string sIGNATUREField;
        
        private string tIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
                this.RaisePropertyChanged("AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CRN {
            get {
                return this.cRNField;
            }
            set {
                this.cRNField = value;
                this.RaisePropertyChanged("CRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MID {
            get {
                return this.mIDField;
            }
            set {
                this.mIDField = value;
                this.RaisePropertyChanged("MID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string REFERALADRESS {
            get {
                return this.rEFERALADRESSField;
            }
            set {
                this.rEFERALADRESSField = value;
                this.RaisePropertyChanged("REFERALADRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SIGNATURE {
            get {
                return this.sIGNATUREField;
            }
            set {
                this.sIGNATUREField = value;
                this.RaisePropertyChanged("SIGNATURE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
                this.RaisePropertyChanged("TID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://token.ws.web.cnpg/")]
    public partial class tokenResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultField;
        
        private string signatureField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservation", WrapperNamespace="http://token.ws.web.cnpg/", IsWrapped=true)]
    public partial class reservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://token.ws.web.cnpg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SamWeb.Mabnacard.TokenSpace.tokenDTO Token_param;
        
        public reservationRequest() {
        }
        
        public reservationRequest(SamWeb.Mabnacard.TokenSpace.tokenDTO Token_param) {
            this.Token_param = Token_param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservationResponse", WrapperNamespace="http://token.ws.web.cnpg/", IsWrapped=true)]
    public partial class reservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://token.ws.web.cnpg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SamWeb.Mabnacard.TokenSpace.tokenResponse @return;
        
        public reservationResponse() {
        }
        
        public reservationResponse(SamWeb.Mabnacard.TokenSpace.tokenResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TokenServiceChannel : SamWeb.Mabnacard.TokenSpace.TokenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenServiceClient : System.ServiceModel.ClientBase<SamWeb.Mabnacard.TokenSpace.TokenService>, SamWeb.Mabnacard.TokenSpace.TokenService {
        
        public TokenServiceClient() {
        }
        
        public TokenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SamWeb.Mabnacard.TokenSpace.reservationResponse SamWeb.Mabnacard.TokenSpace.TokenService.reservation(SamWeb.Mabnacard.TokenSpace.reservationRequest request) {
            return base.Channel.reservation(request);
        }
        
        public SamWeb.Mabnacard.TokenSpace.tokenResponse reservation(SamWeb.Mabnacard.TokenSpace.tokenDTO Token_param) {
            SamWeb.Mabnacard.TokenSpace.reservationRequest inValue = new SamWeb.Mabnacard.TokenSpace.reservationRequest();
            inValue.Token_param = Token_param;
            SamWeb.Mabnacard.TokenSpace.reservationResponse retVal = ((SamWeb.Mabnacard.TokenSpace.TokenService)(this)).reservation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SamWeb.Mabnacard.TokenSpace.reservationResponse> SamWeb.Mabnacard.TokenSpace.TokenService.reservationAsync(SamWeb.Mabnacard.TokenSpace.reservationRequest request) {
            return base.Channel.reservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SamWeb.Mabnacard.TokenSpace.reservationResponse> reservationAsync(SamWeb.Mabnacard.TokenSpace.tokenDTO Token_param) {
            SamWeb.Mabnacard.TokenSpace.reservationRequest inValue = new SamWeb.Mabnacard.TokenSpace.reservationRequest();
            inValue.Token_param = Token_param;
            return ((SamWeb.Mabnacard.TokenSpace.TokenService)(this)).reservationAsync(inValue);
        }
    }
}
