// <auto-generated />
namespace SamClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Consolation_FieldsChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Consolation_FieldsChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201706160910249_Consolation_FieldsChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
