//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamAPI.Mabnacard.ReverseSpace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mabnacard.com/", ConfigurationName="Mabnacard.ReverseSpace.ReverseTransaction")]
    public interface ReverseTransaction {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mabnacard.com/ReverseTransaction/sendReversalRequest", ReplyAction="http://www.mabnacard.com/ReverseTransaction/sendReversalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SamAPI.Mabnacard.ReverseSpace.sendReversalResponse sendReversal(SamAPI.Mabnacard.ReverseSpace.sendReversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mabnacard.com/ReverseTransaction/sendReversalRequest", ReplyAction="http://www.mabnacard.com/ReverseTransaction/sendReversalResponse")]
        System.Threading.Tasks.Task<SamAPI.Mabnacard.ReverseSpace.sendReversalResponse> sendReversalAsync(SamAPI.Mabnacard.ReverseSpace.sendReversalRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mabnacard.com/")]
    public partial class reversalDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mIDField;
        
        private string rRNField;
        
        private string sIGNATUREField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MID {
            get {
                return this.mIDField;
            }
            set {
                this.mIDField = value;
                this.RaisePropertyChanged("MID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RRN {
            get {
                return this.rRNField;
            }
            set {
                this.rRNField = value;
                this.RaisePropertyChanged("RRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SIGNATURE {
            get {
                return this.sIGNATUREField;
            }
            set {
                this.sIGNATUREField = value;
                this.RaisePropertyChanged("SIGNATURE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendReversal", WrapperNamespace="http://www.mabnacard.com/", IsWrapped=true)]
    public partial class sendReversalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mabnacard.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SamAPI.Mabnacard.ReverseSpace.reversalDto Reverse_params;
        
        public sendReversalRequest() {
        }
        
        public sendReversalRequest(SamAPI.Mabnacard.ReverseSpace.reversalDto Reverse_params) {
            this.Reverse_params = Reverse_params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendReversalResponse", WrapperNamespace="http://www.mabnacard.com/", IsWrapped=true)]
    public partial class sendReversalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mabnacard.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendReversalResponse() {
        }
        
        public sendReversalResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReverseTransactionChannel : SamAPI.Mabnacard.ReverseSpace.ReverseTransaction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReverseTransactionClient : System.ServiceModel.ClientBase<SamAPI.Mabnacard.ReverseSpace.ReverseTransaction>, SamAPI.Mabnacard.ReverseSpace.ReverseTransaction {
        
        public ReverseTransactionClient() {
        }
        
        public ReverseTransactionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReverseTransactionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReverseTransactionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReverseTransactionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SamAPI.Mabnacard.ReverseSpace.sendReversalResponse SamAPI.Mabnacard.ReverseSpace.ReverseTransaction.sendReversal(SamAPI.Mabnacard.ReverseSpace.sendReversalRequest request) {
            return base.Channel.sendReversal(request);
        }
        
        public string sendReversal(SamAPI.Mabnacard.ReverseSpace.reversalDto Reverse_params) {
            SamAPI.Mabnacard.ReverseSpace.sendReversalRequest inValue = new SamAPI.Mabnacard.ReverseSpace.sendReversalRequest();
            inValue.Reverse_params = Reverse_params;
            SamAPI.Mabnacard.ReverseSpace.sendReversalResponse retVal = ((SamAPI.Mabnacard.ReverseSpace.ReverseTransaction)(this)).sendReversal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SamAPI.Mabnacard.ReverseSpace.sendReversalResponse> SamAPI.Mabnacard.ReverseSpace.ReverseTransaction.sendReversalAsync(SamAPI.Mabnacard.ReverseSpace.sendReversalRequest request) {
            return base.Channel.sendReversalAsync(request);
        }
        
        public System.Threading.Tasks.Task<SamAPI.Mabnacard.ReverseSpace.sendReversalResponse> sendReversalAsync(SamAPI.Mabnacard.ReverseSpace.reversalDto Reverse_params) {
            SamAPI.Mabnacard.ReverseSpace.sendReversalRequest inValue = new SamAPI.Mabnacard.ReverseSpace.sendReversalRequest();
            inValue.Reverse_params = Reverse_params;
            return ((SamAPI.Mabnacard.ReverseSpace.ReverseTransaction)(this)).sendReversalAsync(inValue);
        }
    }
}
