// <auto-generated />
namespace SamClientDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BannerSupportAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BannerSupportAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201709201426160_BannerSupportAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
