// <auto-generated />
namespace SamClientDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Template_CategoryFieldExcluded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Template_CategoryFieldExcluded));
        
        string IMigrationMetadata.Id
        {
            get { return "201712101005438_Template_CategoryFieldExcluded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
