// <auto-generated />
namespace SamDataAccess.Migrations.SamDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SystemParameters_LastDisplayReportDateFieldAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SystemParameters_LastDisplayReportDateFieldAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201802050612567_SystemParameters_LastDisplayReportDateFieldAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
