//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SmsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SamAPI.Resources.SmsMessages", typeof(SmsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * سام *
        ///کاربر گرامی، پیام تسلیت شما تأیید شده و در صف نمایش قرار گرفت.
        ///کد رهگیری: {0}.
        /// </summary>
        public static string ConsolationConfirmSms {
            get {
                return ResourceManager.GetString("ConsolationConfirmSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * سام *
        ///کاربر گرامی، پیام تسلیت شما در سیستم ثبت گردید، پس از تأیید توسط کارشناس در مسجد به نمایش در خواهد آمد.
        ///کد رهگیری: {0}.
        /// </summary>
        public static string ConsolationCreationSms {
            get {
                return ResourceManager.GetString("ConsolationCreationSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * سام *
        ///کاربر گرامی، پیام تسلیت شما در مراسم به نمایش در آمد.
        ///کد رهگیری: {0}.
        /// </summary>
        public static string ConsolationDisplaySms {
            get {
                return ResourceManager.GetString("ConsolationDisplaySms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * سام *
        ///مراسم با عنوان ({0}) در سیستم ثبت شد.
        ///کد رهگیری: {1}.
        /// </summary>
        public static string ObitCreationSms {
            get {
                return ResourceManager.GetString("ObitCreationSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * سام *
        ///اپراتور محترم، {0} پیام منتظر تأیید در سیستم وجود دارد..
        /// </summary>
        public static string OperatorNotificationMessage {
            get {
                return ResourceManager.GetString("OperatorNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * سام *
        ///کاربر گرامی، با توجه به عدم امکان نمایش پیام تسلیت ارسال شده شما در مراسم مورد نظر، ضمن عرض پوزش، مبلغ پرداخت شده به حساب شما عودت داده شد.
        ///کد رهگیری: {0}.
        /// </summary>
        public static string ReverseSms {
            get {
                return ResourceManager.GetString("ReverseSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #سام_گیف.
        /// </summary>
        public static string TelegramGifsHashtag {
            get {
                return ResourceManager.GetString("TelegramGifsHashtag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان.
        /// </summary>
        public static string TelegramHoldingTime {
            get {
                return ResourceManager.GetString("TelegramHoldingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام های تسلیت ارسالی.
        /// </summary>
        public static string TelegramMessagesCount {
            get {
                return ResourceManager.GetString("TelegramMessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل برگزاری.
        /// </summary>
        public static string TelegramObitPlace {
            get {
                return ResourceManager.GetString("TelegramObitPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراسم.
        /// </summary>
        public static string TelegramObitTitle {
            get {
                return ResourceManager.GetString("TelegramObitTitle", resourceCulture);
            }
        }
    }
}
