//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamUxLib.Resources.Values {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SamUxLib.Resources.Values.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلس چهلم.
        /// </summary>
        public static string ObitType_chehelom {
            get {
                return ResourceManager.GetString("ObitType_chehelom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز هفتم.
        /// </summary>
        public static string ObitType_haftom {
            get {
                return ResourceManager.GetString("ObitType_haftom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالگرد.
        /// </summary>
        public static string ObitType_salgard {
            get {
                return ResourceManager.GetString("ObitType_salgard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر.
        /// </summary>
        public static string ObitType_sayer {
            get {
                return ResourceManager.GetString("ObitType_sayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز سوم.
        /// </summary>
        public static string ObitType_sevom {
            get {
                return ResourceManager.GetString("ObitType_sevom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلس ترحیم.
        /// </summary>
        public static string ObitType_tarhim {
            get {
                return ResourceManager.GetString("ObitType_tarhim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلس یادبود.
        /// </summary>
        public static string ObitType_yadbood {
            get {
                return ResourceManager.GetString("ObitType_yadbood", resourceCulture);
            }
        }
    }
}
