//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamUxLib.Resources.Values {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SamUxLib.Resources.Values.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیاد.
        /// </summary>
        public static string BannerPriority_above_normal {
            get {
                return ResourceManager.GetString("BannerPriority_above_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کم.
        /// </summary>
        public static string BannerPriority_below_normal {
            get {
                return ResourceManager.GetString("BannerPriority_below_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسیار زیاد.
        /// </summary>
        public static string BannerPriority_high {
            get {
                return ResourceManager.GetString("BannerPriority_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسیار کم.
        /// </summary>
        public static string BannerPriority_low {
            get {
                return ResourceManager.GetString("BannerPriority_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادی.
        /// </summary>
        public static string BannerPriority_normal {
            get {
                return ResourceManager.GetString("BannerPriority_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه ای.
        /// </summary>
        public static string BannerType_area {
            get {
                return ResourceManager.GetString("BannerType_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سراسری.
        /// </summary>
        public static string BannerType_global {
            get {
                return ResourceManager.GetString("BannerType_global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختص مراسم.
        /// </summary>
        public static string BannerType_holding {
            get {
                return ResourceManager.GetString("BannerType_holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختص مسجد.
        /// </summary>
        public static string BannerType_mosque {
            get {
                return ResourceManager.GetString("BannerType_mosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو شده.
        /// </summary>
        public static string ConsolationStatus_canceled {
            get {
                return ResourceManager.GetString("ConsolationStatus_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید شده.
        /// </summary>
        public static string ConsolationStatus_confirmed {
            get {
                return ResourceManager.GetString("ConsolationStatus_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش یافته.
        /// </summary>
        public static string ConsolationStatus_displayed {
            get {
                return ResourceManager.GetString("ConsolationStatus_displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر تأیید.
        /// </summary>
        public static string ConsolationStatus_pending {
            get {
                return ResourceManager.GetString("ConsolationStatus_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال شده جهت نمایش.
        /// </summary>
        public static string ConsolationStatus_synced {
            get {
                return ResourceManager.GetString("ConsolationStatus_synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلس چهلم.
        /// </summary>
        public static string ObitType_chehelom {
            get {
                return ResourceManager.GetString("ObitType_chehelom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز هفتم.
        /// </summary>
        public static string ObitType_haftom {
            get {
                return ResourceManager.GetString("ObitType_haftom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالگرد.
        /// </summary>
        public static string ObitType_salgard {
            get {
                return ResourceManager.GetString("ObitType_salgard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر.
        /// </summary>
        public static string ObitType_sayer {
            get {
                return ResourceManager.GetString("ObitType_sayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز سوم.
        /// </summary>
        public static string ObitType_sevom {
            get {
                return ResourceManager.GetString("ObitType_sevom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلس ترحیم.
        /// </summary>
        public static string ObitType_tarhim {
            get {
                return ResourceManager.GetString("ObitType_tarhim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلس یادبود.
        /// </summary>
        public static string ObitType_yadbood {
            get {
                return ResourceManager.GetString("ObitType_yadbood", resourceCulture);
            }
        }
    }
}
