//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamUxLib.Resources.Values {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SamUxLib.Resources.Values.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، حساب کاربری شما غیرفعال شده است، لطفاً با واحد پشتیبانی سیستم تماس بگیرید..
        /// </summary>
        public static string AccountDisabled {
            get {
                return ResourceManager.GetString("AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در ارتباط با سرور رخ داده است، لطفاً ارتباط اینترنت خود را بررسی و مجدداً تلاش کنید..
        /// </summary>
        public static string ApiErrorMessage {
            get {
                return ResourceManager.GetString("ApiErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا نسبت به اجرای عملیات حذف اطمینان دارید؟.
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه مشکلی در پرداخت و یا ارسال پیام شما رخ داده است، لطفاً مجدداً تلاش کنید..
        /// </summary>
        public static string ConsolationSendingFailed {
            get {
                return ResourceManager.GetString("ConsolationSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام تسلیت شما با موفقیت در سیستم ثبت شد و پس از تأیید نمایش داده خواهد شد. هرگونه تغییر وضعیت از طریق پیامک به اطلاع شما خواهد رسید..
        /// </summary>
        public static string ConsolationSuccessfullySent {
            get {
                return ResourceManager.GetString("ConsolationSuccessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت هرگونه پیشنهاد یا انتقاد می توانید از طریق راه های ارتباطی زیر می توانید با مدیریت سیستم در ارتباط باشید:.
        /// </summary>
        public static string ContactUsText {
            get {
                return ResourceManager.GetString("ContactUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، پیام شما در سیستم ثبت گردید و پس از اتمام مراحل پرداخت در سریع ترین زمان مناسب نمایش خواهد یافت، جهت رفتن به سایت بانک برای پرداخت مبلغ دکمه (تأیید و پرداخت) در پایین صفحه را فشار دهید. نحوه نمایش پیام شما در نمایشگر به صورت زیر خواهد بود:.
        /// </summary>
        public static string CreateConsolationPreviewStepExplanation {
            get {
                return ResourceManager.GetString("CreateConsolationPreviewStepExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، پیام شما در سیستم ثبت گردید و در سریع ترین زمان مناسب نمایش خواهد یافت (بصورت رایگان). نحوه نمایش پیام شما در نمایشگر به صورت زیر خواهد بود:.
        /// </summary>
        public static string CreateConsolationPreviewStepExplanationFree {
            get {
                return ResourceManager.GetString("CreateConsolationPreviewStepExplanationFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متأسفانه خطایی در پردازش درخواست شما رخ داده است، لطفاً مجدداً تلاش کنید..
        /// </summary>
        public static string CustomErrorMessage {
            get {
                return ResourceManager.GetString("CustomErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با حذف دسته، تمامی الگوهای آن دسته حذف خواهد شد (شما قادر به حذف الگوهای استفاده شده نخواهید بود)
        ///
        ///آیا اطمینان دارید؟.
        /// </summary>
        public static string DeleteCategoryWarning {
            get {
                return ResourceManager.GetString("DeleteCategoryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت دریافت اپلیکیشن سام بر روی لینک زیر کلیک کنید:.
        /// </summary>
        public static string DownloadAppDesc {
            get {
                return ResourceManager.GetString("DownloadAppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت دانلود آلبوم لطفاً بر روی لینک زیر کلیک کنید..
        /// </summary>
        public static string DownloadCatalogText {
            get {
                return ResourceManager.GetString("DownloadCatalogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی با این نام قبلا ثبت شده است..
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری وارد شده قبلا ثبت شده است..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است، لطفاً مجدداً تلاش کنید..
        /// </summary>
        public static string ErrorOccurredTryAgain {
            get {
                return ResourceManager.GetString("ErrorOccurredTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً مقادیر فرم را پر کنید..
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبل از اینکه بتوانید الگو را طراحی کنید لازم است تصویر پس زمینه و ابعاد الگو را مشخص کنید..
        /// </summary>
        public static string FillBeforeDesignTemplate {
            get {
                return ResourceManager.GetString("FillBeforeDesignTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً مقدار فیلدهای اجباری را مشخص نمایید..
        /// </summary>
        public static string FillRequiredFields {
            get {
                return ResourceManager.GetString("FillRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت اطلاع رسانی وضعیت پیام استفاده خواهد شد..
        /// </summary>
        public static string Hint_CellPhoneNumber {
            get {
                return ResourceManager.GetString("Hint_CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فیلد در پیام تسلیت نمایش داده نخواهد شد..
        /// </summary>
        public static string Hint_FullName {
            get {
                return ResourceManager.GetString("Hint_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده معتبر نیست..
        /// </summary>
        public static string Invalid_CellPhoneNumber {
            get {
                return ResourceManager.GetString("Invalid_CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شماره همراه وارد شده صحیح نمی باشد..
        /// </summary>
        public static string InvalidCellPhone {
            get {
                return ResourceManager.GetString("InvalidCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقادیر وارد شده معتبر نیستند، لطفاً اصلاح کرده و مجدداً تلاش کنید..
        /// </summary>
        public static string InvalidInputValues {
            get {
                return ResourceManager.GetString("InvalidInputValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه وارد شده صحیح نیست، لطفاً مجدداً تلاش کنید..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور صحیح نیست..
        /// </summary>
        public static string InvalidPasswordConfirmation {
            get {
                return ResourceManager.GetString("InvalidPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت گذرواژه وارد شده صحیح نیست..
        /// </summary>
        public static string InvalidPasswordFormat {
            get {
                return ResourceManager.GetString("InvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شماره تلفن وارد شده صحیح نمی باشد..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان وارد شده برای نقش دارای فرمت صحیح نیست..
        /// </summary>
        public static string InvalidRoleNameFormat {
            get {
                return ResourceManager.GetString("InvalidRoleNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری وارد شده صحیح نیست، لطفاً پس از اصلاح مجدداً تلاش کنید..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت نام کاربری وارد شده صحیح نیست..
        /// </summary>
        public static string InvalidUserNameFormat {
            get {
                return ResourceManager.GetString("InvalidUserNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم ناموفق بود، لطفاً مجدداً تلاش کنید..
        /// </summary>
        public static string LoginFailedTryAgain {
            get {
                return ResourceManager.GetString("LoginFailedTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده برای فاصله زمانی مجاز نیست..
        /// </summary>
        public static string MinIntervalIncorrect {
            get {
                return ResourceManager.GetString("MinIntervalIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موردی جهت نمایش یافت نشد..
        /// </summary>
        public static string NoItem {
            get {
                return ResourceManager.GetString("NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف این مورد از سیستم مجاز نیست..
        /// </summary>
        public static string NotAllowedToDeleteItem {
            get {
                return ResourceManager.GetString("NotAllowedToDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات پرداخت از طرف کاربر لغو شد..
        /// </summary>
        public static string PaymentCanceled {
            get {
                return ResourceManager.GetString("PaymentCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در فرایند پرداخت، در صورت کسر وجه از حساب شما به زودی مبلغ کسر شده به حساب باز خواهد گشت..
        /// </summary>
        public static string PaymentError {
            get {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت با موفقیت انجام شد..
        /// </summary>
        public static string PaymentSuccessfull {
            get {
                return ResourceManager.GetString("PaymentSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً یک یا چند شرط از موارد فوق را مشخص نمایید..
        /// </summary>
        public static string PleaseFillSomeConditions {
            get {
                return ResourceManager.GetString("PleaseFillSomeConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً شماره موبایل خود را وارد کنید..
        /// </summary>
        public static string Required_CellPhoneNumber {
            get {
                return ResourceManager.GetString("Required_CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام و نام خانوادگی خود را وارد کنید..
        /// </summary>
        public static string Required_FullName {
            get {
                return ResourceManager.GetString("Required_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت ادامه لطفاً ابتدا مجلس ترحیم مورد نظر خود را انتخاب نمایید..
        /// </summary>
        public static string Required_Obit {
            get {
                return ResourceManager.GetString("Required_Obit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت ادامه لطفاً الگوی پیام تسلیت خود را انتخاب نمایید..
        /// </summary>
        public static string Required_Template {
            get {
                return ResourceManager.GetString("Required_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً گذرواژه خود را وارد کنید..
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام کاربری خود را وارد نمایید..
        /// </summary>
        public static string RequiredUserName {
            get {
                return ResourceManager.GetString("RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبل از همگام سازی می بایست تنظیمات کلاینت را ذخیره کنید..
        /// </summary>
        public static string SetSettingsBeforeSync {
            get {
                return ResourceManager.GetString("SetSettingsBeforeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متأسفانه مشکلی بروز کرده است، لطفاً مجدداً تلاش کنید..
        /// </summary>
        public static string SomthingWrongHappend {
            get {
                return ResourceManager.GetString("SomthingWrongHappend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین اطلاعات برگزاری مراسم الزامی است..
        /// </summary>
        public static string SpecifyAtLeastOneHolding {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین حداقل یک سالن برای مسجد الزامی است..
        /// </summary>
        public static string SpecifyAtLeastOneSaloon {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneSaloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً شهر یا استان مورد نظر را انتخاب نمایید..
        /// </summary>
        public static string SpecifyBannerArea {
            get {
                return ResourceManager.GetString("SpecifyBannerArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً مراسم مورد نظر خود را انتخاب نمایید..
        /// </summary>
        public static string SpecifyHolding {
            get {
                return ResourceManager.GetString("SpecifyHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً مسجد مورد نظر خود را انتخاب کنید..
        /// </summary>
        public static string SpecifyMosque {
            get {
                return ResourceManager.GetString("SpecifyMosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد..
        /// </summary>
        public static string SuccessfullyDone {
            get {
                return ResourceManager.GetString("SuccessfullyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نقش مدیر پیش فرض سیستم قابل تغییر نمی باشد..
        /// </summary>
        public static string SysAdminRoleNameImutable {
            get {
                return ResourceManager.GetString("SysAdminRoleNameImutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری مدیر پیش فرض سیستم قابل تغییر نمی باشد..
        /// </summary>
        public static string SysAdminUserNameImutable {
            get {
                return ResourceManager.GetString("SysAdminUserNameImutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار تکمیل عملیات پرداخت...
        ///
        ///لطفاً از طریق دستگاه کارتخوان عملیات پرداخت را انجام دهید..
        /// </summary>
        public static string WaitForPosMessage {
            get {
                return ResourceManager.GetString("WaitForPosMessage", resourceCulture);
            }
        }
    }
}
