//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamUxLib.Resources.Values {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SamUxLib.Resources.Values.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره سیستم.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره پروژه سام.
        /// </summary>
        public static string AboutSam {
            get {
                return ResourceManager.GetString("AboutSam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در راستای بهره گیری از فناوری اطلاعات در حوزه های دینی، فرهنگی و اجتماعی با هدف کمک به یاری به حفظ و ارتقاء کیفیت مدیریت مساجد و جلوگیری از اتلاف هزینه های هنگفت برای چاپ و نصب بنر های و اعلامیه های تسلیت در مجالس ترحیم، کمک به محیط زیست از طریق کاهش مصرف بنرهای پلاستیکی و نیز کمک به هزینه های مالی مساجد، سیستم اطلاع رسانی مساجد «سام» ابداع ، طراحی و راه اندازی شده است.
        ///در این سیستم ، یک شبکه الکترونیکی بهم پیوسته از نمایشگر های بزرگ متصل به هم که توسط نرم افزار های هوشمند مدیریت می گردند ، اعلامیه های تسل [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutSamExplanation {
            get {
                return ResourceManager.GetString("AboutSamExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی.
        /// </summary>
        public static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطوح دسترسی.
        /// </summary>
        public static string AccessLevels {
            get {
                return ResourceManager.GetString("AccessLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب های کاربری.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیر سیستم.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چیدمان.
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ قابل پرداخت.
        /// </summary>
        public static string AmountToPay {
            get {
                return ResourceManager.GetString("AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه اطلاع رسانی مساجد.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سام.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری فعال.
        /// </summary>
        public static string ApprovedAccount {
            get {
                return ResourceManager.GetString("ApprovedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سام.
        /// </summary>
        public static string AppShortName {
            get {
                return ResourceManager.GetString("AppShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه اطلاع رسانی مساجد.
        /// </summary>
        public static string AppShortNameDesc {
            get {
                return ResourceManager.GetString("AppShortNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد.
        /// </summary>
        public static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش خودکار پبام های تسلیت حین مراسم.
        /// </summary>
        public static string AutoSlideShow {
            get {
                return ResourceManager.GetString("AutoSlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر پس زمینه.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به صفحه اصلی.
        /// </summary>
        public static string BackToMainPage {
            get {
                return ResourceManager.GetString("BackToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنرها.
        /// </summary>
        public static string Banners {
            get {
                return ResourceManager.GetString("Banners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع بنر.
        /// </summary>
        public static string BannerType {
            get {
                return ResourceManager.GetString("BannerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پایه.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت شروع.
        /// </summary>
        public static string BeginHour {
            get {
                return ResourceManager.GetString("BeginHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوشته ضخیم.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایین.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو تأیید.
        /// </summary>
        public static string CancelConfirmation {
            get {
                return ResourceManager.GetString("CancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو نمایش.
        /// </summary>
        public static string CancelDisplay {
            get {
                return ResourceManager.GetString("CancelDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه.
        /// </summary>
        public static string CellPhoneNumber {
            get {
                return ResourceManager.GetString("CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسط.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات کلاینت.
        /// </summary>
        public static string ClientSettings {
            get {
                return ResourceManager.GetString("ClientSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن پنجره.
        /// </summary>
        public static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید و ادامه.
        /// </summary>
        public static string ConfirmAndContinue {
            get {
                return ResourceManager.GetString("ConfirmAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید و پرداخت.
        /// </summary>
        public static string ConfirmAndPay {
            get {
                return ResourceManager.GetString("ConfirmAndPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید و پیش نمایش.
        /// </summary>
        public static string ConfirmAndPreview {
            get {
                return ResourceManager.GetString("ConfirmAndPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید جهت نمایش.
        /// </summary>
        public static string ConfirmToDisplay {
            get {
                return ResourceManager.GetString("ConfirmToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ارتباط.
        /// </summary>
        public static string ConnectionInfo {
            get {
                return ResourceManager.GetString("ConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام های تسلیت.
        /// </summary>
        public static string Consolations {
            get {
                return ResourceManager.GetString("Consolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو شده.
        /// </summary>
        public static string ConsolationStatus_Canceled {
            get {
                return ResourceManager.GetString("ConsolationStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید شده.
        /// </summary>
        public static string ConsolationStatus_Confirmed {
            get {
                return ResourceManager.GetString("ConsolationStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش یافته.
        /// </summary>
        public static string ConsolationStatus_Displayed {
            get {
                return ResourceManager.GetString("ConsolationStatus_Displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر تأیید.
        /// </summary>
        public static string ConsolationStatus_Pending {
            get {
                return ResourceManager.GetString("ConsolationStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کننده پیام.
        /// </summary>
        public static string Consolator {
            get {
                return ResourceManager.GetString("Consolator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد بنر جدید.
        /// </summary>
        public static string CreateBanner {
            get {
                return ResourceManager.GetString("CreateBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        public static string CreateConsolationCustomerInfoStep {
            get {
                return ResourceManager.GetString("CreateConsolationCustomerInfoStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب مجلس ترحیم.
        /// </summary>
        public static string CreateConsolationObitSelectionStep {
            get {
                return ResourceManager.GetString("CreateConsolationObitSelectionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نمایش.
        /// </summary>
        public static string CreateConsolationPreviewStep {
            get {
                return ResourceManager.GetString("CreateConsolationPreviewStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان عملیات.
        /// </summary>
        public static string CreateConsolationSuccessStep {
            get {
                return ResourceManager.GetString("CreateConsolationSuccessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای پیام تسلیت.
        /// </summary>
        public static string CreateConsolationTemplateInfoStep {
            get {
                return ResourceManager.GetString("CreateConsolationTemplateInfoStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب الگوی پیام تسلیت.
        /// </summary>
        public static string CreateConsolationTemplateSelectionStep {
            get {
                return ResourceManager.GetString("CreateConsolationTemplateSelectionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مراسم جدید.
        /// </summary>
        public static string CreateObit {
            get {
                return ResourceManager.GetString("CreateObit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد الگوی جدید.
        /// </summary>
        public static string CreateTemplate {
            get {
                return ResourceManager.GetString("CreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ایجاد.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ثبت کننده.
        /// </summary>
        public static string CreatorUser {
            get {
                return ResourceManager.GetString("CreatorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گام دوم: مشخصات سفارش دهنده.
        /// </summary>
        public static string CustomerInfoStepTitle {
            get {
                return ResourceManager.GetString("CustomerInfoStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است.
        /// </summary>
        public static string CustomErrorTitle {
            get {
                return ResourceManager.GetString("CustomErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه متوفی.
        /// </summary>
        public static string DeceasedIdentifier {
            get {
                return ResourceManager.GetString("DeceasedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پیش فرض نمایش (ثانیه).
        /// </summary>
        public static string DefaultSlideShowDuration {
            get {
                return ResourceManager.GetString("DefaultSlideShowDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان نمایش (ثانیه).
        /// </summary>
        public static string DisplayDurationInSeconds {
            get {
                return ResourceManager.GetString("DisplayDurationInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام جهت نمایش.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اَپ.
        /// </summary>
        public static string DownloadApp {
            get {
                return ResourceManager.GetString("DownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأخیر اولیه بروزرسانی (ثانیه).
        /// </summary>
        public static string DownloadDelaySeconds {
            get {
                return ResourceManager.GetString("DownloadDelaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاصله بروزرسانی ها (ثانیه).
        /// </summary>
        public static string DownloadIntervalSeconds {
            get {
                return ResourceManager.GetString("DownloadIntervalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آلبوم پیام.
        /// </summary>
        public static string DownloadResume {
            get {
                return ResourceManager.GetString("DownloadResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش بنر.
        /// </summary>
        public static string EditBanner {
            get {
                return ResourceManager.GetString("EditBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پیام تسلیت.
        /// </summary>
        public static string EditConsolation {
            get {
                return ResourceManager.GetString("EditConsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش فیلد الگو.
        /// </summary>
        public static string EditField {
            get {
                return ResourceManager.GetString("EditField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات مسجد.
        /// </summary>
        public static string EditMosque {
            get {
                return ResourceManager.GetString("EditMosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مراسم.
        /// </summary>
        public static string EditObit {
            get {
                return ResourceManager.GetString("EditObit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش الگو.
        /// </summary>
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش حساب کاربری.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت پایان.
        /// </summary>
        public static string EndHour {
            get {
                return ResourceManager.GetString("EndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string ErrorMessageBoxCaption {
            get {
                return ResourceManager.GetString("ErrorMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکانات سیستم.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فونت.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول شرکت آرت استون ایرانیان.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی و تولید: شرکت آرت استون ایرانیان.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایگان.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات عمومی.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنمای استفاده.
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه استفادهنحوه است [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowToUseExplanation {
            get {
                return ResourceManager.GetString("HowToUseExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسیار بزرگ.
        /// </summary>
        public static string Huge {
            get {
                return ResourceManager.GetString("Huge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه امام جماعت.
        /// </summary>
        public static string ImamCellPhone {
            get {
                return ResourceManager.GetString("ImamCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام امام جماعت.
        /// </summary>
        public static string ImamName {
            get {
                return ResourceManager.GetString("ImamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه رابط.
        /// </summary>
        public static string InterfaceCellPhone {
            get {
                return ResourceManager.GetString("InterfaceCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام رابط.
        /// </summary>
        public static string InterfaceName {
            get {
                return ResourceManager.GetString("InterfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاصله تکرار (به اسلاید).
        /// </summary>
        public static string IntervalInSlides {
            get {
                return ResourceManager.GetString("IntervalInSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی پی.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگ.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین بروزرسانی.
        /// </summary>
        public static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدیدترین مساجد عضو شبکه.
        /// </summary>
        public static string LatestMosques {
            get {
                return ResourceManager.GetString("LatestMosques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین.
        /// </summary>
        public static string LatinName {
            get {
                return ResourceManager.GetString("LatinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چپ.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چپ به راست.
        /// </summary>
        public static string LeftToRightDirection {
            get {
                return ResourceManager.GetString("LeftToRightDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع اعتبار.
        /// </summary>
        public static string LifeBeginTime {
            get {
                return ResourceManager.GetString("LifeBeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پایان اعتبار.
        /// </summary>
        public static string LifeEndTime {
            get {
                return ResourceManager.GetString("LifeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظارت زنده.
        /// </summary>
        public static string LiveStatus {
            get {
                return ResourceManager.GetString("LiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت مکانی.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم.
        /// </summary>
        public static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نگهداری سیستم.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام.
        /// </summary>
        public static string MessageBoxCaption {
            get {
                return ResourceManager.GetString("MessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظارت.
        /// </summary>
        public static string Monitoring {
            get {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسجد.
        /// </summary>
        public static string Mosque {
            get {
                return ResourceManager.GetString("Mosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساجد عضو.
        /// </summary>
        public static string MosqueBrowser {
            get {
                return ResourceManager.GetString("MosqueBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات مسجد.
        /// </summary>
        public static string MosqueDetails {
            get {
                return ResourceManager.GetString("MosqueDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مسجد.
        /// </summary>
        public static string MosqueInfo {
            get {
                return ResourceManager.GetString("MosqueInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مسجد.
        /// </summary>
        public static string MosqueName {
            get {
                return ResourceManager.GetString("MosqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مساجد.
        /// </summary>
        public static string Mosques {
            get {
                return ResourceManager.GetString("Mosques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساجد و مراسمات.
        /// </summary>
        public static string MosquesAndObits {
            get {
                return ResourceManager.GetString("MosquesAndObits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته جدید.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد جدید.
        /// </summary>
        public static string NewField {
            get {
                return ResourceManager.GetString("NewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسجد جدید.
        /// </summary>
        public static string NewMosque {
            get {
                return ResourceManager.GetString("NewMosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش جدید.
        /// </summary>
        public static string NewRole {
            get {
                return ResourceManager.GetString("NewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری جدید.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعدی.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گام بعدی.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معمولی.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراسم.
        /// </summary>
        public static string Obit {
            get {
                return ResourceManager.GetString("Obit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان برگزاری مراسم.
        /// </summary>
        public static string ObitHolding {
            get {
                return ResourceManager.GetString("ObitHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان برگزاری مراسم.
        /// </summary>
        public static string ObitHoldingTime {
            get {
                return ResourceManager.GetString("ObitHoldingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراسم ها.
        /// </summary>
        public static string Obits {
            get {
                return ResourceManager.GetString("Obits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گام اول: انتخاب مراسم.
        /// </summary>
        public static string ObitSelectionStepTitle {
            get {
                return ResourceManager.GetString("ObitSelectionStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رهگیری مراسم.
        /// </summary>
        public static string ObitTrackingNumber {
            get {
                return ResourceManager.GetString("ObitTrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مراسم.
        /// </summary>
        public static string ObitType {
            get {
                return ResourceManager.GetString("ObitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس دفتر مرکزی شرکت.
        /// </summary>
        public static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارومیه، خیابان مولوی، روبروی بانک ملت، ساختمان کوروش، واحد 8.
        /// </summary>
        public static string OfficeAddressText {
            get {
                return ResourceManager.GetString("OfficeAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس شرکت.
        /// </summary>
        public static string OfficeTel {
            get {
                return ResourceManager.GetString("OfficeTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازکردن برنامه.
        /// </summary>
        public static string OpenApplication {
            get {
                return ResourceManager.GetString("OpenApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه اطلاع رسانی.
        /// </summary>
        public static string OwnerCellPhone {
            get {
                return ResourceManager.GetString("OwnerCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسمتی از نام مسجد.
        /// </summary>
        public static string PartOfMosqueName {
            get {
                return ResourceManager.GetString("PartOfMosqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار گذرواژه.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت پرداخت.
        /// </summary>
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت ناموفق.
        /// </summary>
        public static string PaymentStatus_Failed {
            get {
                return ResourceManager.GetString("PaymentStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایگان.
        /// </summary>
        public static string PaymentStatus_Free {
            get {
                return ResourceManager.GetString("PaymentStatus_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر پرداخت.
        /// </summary>
        public static string PaymentStatus_Pending {
            get {
                return ResourceManager.GetString("PaymentStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به حساب.
        /// </summary>
        public static string PaymentStatus_Reversed {
            get {
                return ResourceManager.GetString("PaymentStatus_Reversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر تأیید نهایی.
        /// </summary>
        public static string PaymentStatus_Succeeded {
            get {
                return ResourceManager.GetString("PaymentStatus_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شده.
        /// </summary>
        public static string PaymentStatus_Verified {
            get {
                return ResourceManager.GetString("PaymentStatus_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گام نهایی: تأیید طرح و پرداخت مبلغ.
        /// </summary>
        public static string PayViaPosStepTitle {
            get {
                return ResourceManager.GetString("PayViaPosStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً صبر کنید....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلی.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گام قبلی.
        /// </summary>
        public static string PreviousStep {
            get {
                return ResourceManager.GetString("PreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه (ریال).
        /// </summary>
        public static string PriceInUnit {
            get {
                return ResourceManager.GetString("PriceInUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        public static string PriceUnit {
            get {
                return ResourceManager.GetString("PriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولویت.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان / شهر.
        /// </summary>
        public static string ProvinceCity {
            get {
                return ResourceManager.GetString("ProvinceCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت ادامه پاسخ دهید.
        /// </summary>
        public static string QuestionMessageBoxCaption {
            get {
                return ResourceManager.GetString("QuestionMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از برنامه.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواندن.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت پیام تسلیت.
        /// </summary>
        public static string RegisterConsolation {
            get {
                return ResourceManager.GetString("RegisterConsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع گزارش.
        /// </summary>
        public static string ReportBeginDate {
            get {
                return ResourceManager.GetString("ReportBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان گزارش.
        /// </summary>
        public static string ReportEndDate {
            get {
                return ResourceManager.GetString("ReportEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشات.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع گزارش.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش عملکرد روزانه.
        /// </summary>
        public static string ReportType_DailyTurnover {
            get {
                return ResourceManager.GetString("ReportType_DailyTurnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش عملکرد مساجد.
        /// </summary>
        public static string ReportType_MosquesTurnover {
            get {
                return ResourceManager.GetString("ReportType_MosquesTurnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش عملکرد مساجد (نمودار).
        /// </summary>
        public static string ReportType_MosquesTurnoverChart {
            get {
                return ResourceManager.GetString("ReportType_MosquesTurnoverChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اتصال به دستگاه کارت خوان، مجددا تلاش کنید..
        /// </summary>
        public static string RequestToPOSFailed {
            get {
                return ResourceManager.GetString("RequestToPOSFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلاش مجدد.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به صفحه اصلی.
        /// </summary>
        public static string ReturnToHomePage {
            get {
                return ResourceManager.GetString("ReturnToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راست.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالن.
        /// </summary>
        public static string Saloon {
            get {
                return ResourceManager.GetString("Saloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سالن.
        /// </summary>
        public static string SaloonName {
            get {
                return ResourceManager.GetString("SaloonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالن ها.
        /// </summary>
        public static string Saloons {
            get {
                return ResourceManager.GetString("Saloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب های کاربری.
        /// </summary>
        public static string section_accounts {
            get {
                return ResourceManager.GetString("section_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنرها.
        /// </summary>
        public static string section_banners {
            get {
                return ResourceManager.GetString("section_banners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی الگوها.
        /// </summary>
        public static string section_categories {
            get {
                return ResourceManager.GetString("section_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام های تسلیت.
        /// </summary>
        public static string section_consolations {
            get {
                return ResourceManager.GetString("section_consolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظارت زنده.
        /// </summary>
        public static string section_livestatus {
            get {
                return ResourceManager.GetString("section_livestatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساجد.
        /// </summary>
        public static string section_mosques {
            get {
                return ResourceManager.GetString("section_mosques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراسمات.
        /// </summary>
        public static string section_obits {
            get {
                return ResourceManager.GetString("section_obits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشات.
        /// </summary>
        public static string section_reports {
            get {
                return ResourceManager.GetString("section_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش ها.
        /// </summary>
        public static string section_roles {
            get {
                return ResourceManager.GetString("section_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگوها.
        /// </summary>
        public static string section_templates {
            get {
                return ResourceManager.GetString("section_templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب فایل.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام تسلیت.
        /// </summary>
        public static string SendConsolation {
            get {
                return ResourceManager.GetString("SendConsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرستنده.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ارسال.
        /// </summary>
        public static string SendTime {
            get {
                return ResourceManager.GetString("SendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در آغاز.
        /// </summary>
        public static string ShowOnStart {
            get {
                return ResourceManager.GetString("ShowOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش پی در پی.
        /// </summary>
        public static string SlideShow {
            get {
                return ResourceManager.GetString("SlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوچک.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع سرویس.
        /// </summary>
        public static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف سرویس.
        /// </summary>
        public static string StopService {
            get {
                return ResourceManager.GetString("StopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس همگام ساز.
        /// </summary>
        public static string SyncService {
            get {
                return ResourceManager.GetString("SyncService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همگام سازی با سرور.
        /// </summary>
        public static string SyncWithServer {
            get {
                return ResourceManager.GetString("SyncWithServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلگرام.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگوی پیام.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی الگوها.
        /// </summary>
        public static string TemplateCategories {
            get {
                return ResourceManager.GetString("TemplateCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی الگو.
        /// </summary>
        public static string TemplateDesign {
            get {
                return ResourceManager.GetString("TemplateDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات الگو.
        /// </summary>
        public static string TemplateInfo {
            get {
                return ResourceManager.GetString("TemplateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گام چهارم: محتوای پیام تسلیت.
        /// </summary>
        public static string TemplateInfoStepTitle {
            get {
                return ResourceManager.GetString("TemplateInfoStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام الگو.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگوهای تسلیت.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گام سوم: انتخاب طرح پیام.
        /// </summary>
        public static string TemplateSelectionStepTitle {
            get {
                return ResourceManager.GetString("TemplateSelectionStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این متن در نحوه نمایش الگو تأثیری نخواهد داشت و تنها برای جستجوی الگو استفاده خواهد شد..
        /// </summary>
        public static string TemplateTextComment {
            get {
                return ResourceManager.GetString("TemplateTextComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ متن.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسیار کوچک.
        /// </summary>
        public static string Tiny {
            get {
                return ResourceManager.GetString("Tiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالا.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهگیری پیام.
        /// </summary>
        public static string TrackConsolation {
            get {
                return ResourceManager.GetString("TrackConsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رهگیری پیام.
        /// </summary>
        public static string TrackingNumber {
            get {
                return ResourceManager.GetString("TrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه تراکنش.
        /// </summary>
        public static string TransactionResult {
            get {
                return ResourceManager.GetString("TransactionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات انتشار.
        /// </summary>
        public static string TypeSpecificInformation {
            get {
                return ResourceManager.GetString("TypeSpecificInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرم افزار بروزرسان سام.
        /// </summary>
        public static string UpdaterTitle {
            get {
                return ResourceManager.GetString("UpdaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش نموداری.
        /// </summary>
        public static string ViewChart {
            get {
                return ResourceManager.GetString("ViewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش گزارش.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابل مشاهده.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبت پهنا به ارتفاع.
        /// </summary>
        public static string WidthHeightRatio {
            get {
                return ResourceManager.GetString("WidthHeightRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس های پس زمینه.
        /// </summary>
        public static string WindowsServices {
            get {
                return ResourceManager.GetString("WindowsServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شکستن محتوا.
        /// </summary>
        public static string WrapContent {
            get {
                return ResourceManager.GetString("WrapContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
