//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamUxLib.Resources.Values {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SamUxLib.Resources.Values.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطوح دسترسی.
        /// </summary>
        public static string AccessLevels {
            get {
                return ResourceManager.GetString("AccessLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب های کاربری.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیر سیستم.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چیدمان.
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه اطلاع رسانی مساجد (سام).
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری فعال.
        /// </summary>
        public static string ApprovedAccount {
            get {
                return ResourceManager.GetString("ApprovedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد.
        /// </summary>
        public static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر پس زمینه.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پایه.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت شروع.
        /// </summary>
        public static string BeginHour {
            get {
                return ResourceManager.GetString("BeginHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوشته ضخیم.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایین.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه.
        /// </summary>
        public static string CellPhoneNumber {
            get {
                return ResourceManager.GetString("CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسط.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ارتباط.
        /// </summary>
        public static string ConnectionInfo {
            get {
                return ResourceManager.GetString("ConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام های تسلیت.
        /// </summary>
        public static string Consolations {
            get {
                return ResourceManager.GetString("Consolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کننده پیام.
        /// </summary>
        public static string Consolator {
            get {
                return ResourceManager.GetString("Consolator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مراسم جدید.
        /// </summary>
        public static string CreateObit {
            get {
                return ResourceManager.GetString("CreateObit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد الگوی جدید.
        /// </summary>
        public static string CreateTemplate {
            get {
                return ResourceManager.GetString("CreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ایجاد.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ثبت کننده.
        /// </summary>
        public static string CreatorUser {
            get {
                return ResourceManager.GetString("CreatorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام جهت نمایش.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش فیلد الگو.
        /// </summary>
        public static string EditField {
            get {
                return ResourceManager.GetString("EditField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات مسجد.
        /// </summary>
        public static string EditMosque {
            get {
                return ResourceManager.GetString("EditMosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مراسم.
        /// </summary>
        public static string EditObit {
            get {
                return ResourceManager.GetString("EditObit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش الگو.
        /// </summary>
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش حساب کاربری.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت پایان.
        /// </summary>
        public static string EndHour {
            get {
                return ResourceManager.GetString("EndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string ErrorMessageBoxCaption {
            get {
                return ResourceManager.GetString("ErrorMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فونت.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی و تولید: شرکت آرت استون ایرانیان.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسیار بزرگ.
        /// </summary>
        public static string Huge {
            get {
                return ResourceManager.GetString("Huge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه امام جماعت.
        /// </summary>
        public static string ImamCellPhone {
            get {
                return ResourceManager.GetString("ImamCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام امام جماعت.
        /// </summary>
        public static string ImamName {
            get {
                return ResourceManager.GetString("ImamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه رابط.
        /// </summary>
        public static string InterfaceCellPhone {
            get {
                return ResourceManager.GetString("InterfaceCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام رابط.
        /// </summary>
        public static string InterfaceName {
            get {
                return ResourceManager.GetString("InterfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی پی.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگ.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین بروزرسانی.
        /// </summary>
        public static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین.
        /// </summary>
        public static string LatinName {
            get {
                return ResourceManager.GetString("LatinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چپ.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چپ به راست.
        /// </summary>
        public static string LeftToRightDirection {
            get {
                return ResourceManager.GetString("LeftToRightDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت مکانی.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم.
        /// </summary>
        public static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نگهداری سیستم.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام.
        /// </summary>
        public static string MessageBoxCaption {
            get {
                return ResourceManager.GetString("MessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظارت.
        /// </summary>
        public static string Monitoring {
            get {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسجد.
        /// </summary>
        public static string Mosque {
            get {
                return ResourceManager.GetString("Mosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مسجد.
        /// </summary>
        public static string MosqueName {
            get {
                return ResourceManager.GetString("MosqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مساجد.
        /// </summary>
        public static string Mosques {
            get {
                return ResourceManager.GetString("Mosques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساجد و مراسمات.
        /// </summary>
        public static string MosquesAndObits {
            get {
                return ResourceManager.GetString("MosquesAndObits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته جدید.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد جدید.
        /// </summary>
        public static string NewField {
            get {
                return ResourceManager.GetString("NewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسجد جدید.
        /// </summary>
        public static string NewMosque {
            get {
                return ResourceManager.GetString("NewMosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری جدید.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معمولی.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراسم.
        /// </summary>
        public static string Obit {
            get {
                return ResourceManager.GetString("Obit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان برگزاری مراسم.
        /// </summary>
        public static string ObitHolding {
            get {
                return ResourceManager.GetString("ObitHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراسم ها.
        /// </summary>
        public static string Obits {
            get {
                return ResourceManager.GetString("Obits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مراسم.
        /// </summary>
        public static string ObitType {
            get {
                return ResourceManager.GetString("ObitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار گذرواژه.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً صبر کنید....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه (ریال).
        /// </summary>
        public static string PriceInUnit {
            get {
                return ResourceManager.GetString("PriceInUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        public static string PriceUnit {
            get {
                return ResourceManager.GetString("PriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت ادامه پاسخ دهید.
        /// </summary>
        public static string QuestionMessageBoxCaption {
            get {
                return ResourceManager.GetString("QuestionMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راست.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالن.
        /// </summary>
        public static string Saloon {
            get {
                return ResourceManager.GetString("Saloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سالن.
        /// </summary>
        public static string SaloonName {
            get {
                return ResourceManager.GetString("SaloonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالن ها.
        /// </summary>
        public static string Saloons {
            get {
                return ResourceManager.GetString("Saloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب فایل.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوچک.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همگام سازی با سرور.
        /// </summary>
        public static string SyncWithServer {
            get {
                return ResourceManager.GetString("SyncWithServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگوی پیام.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی الگو.
        /// </summary>
        public static string TemplateDesign {
            get {
                return ResourceManager.GetString("TemplateDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات الگو.
        /// </summary>
        public static string TemplateInfo {
            get {
                return ResourceManager.GetString("TemplateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام الگو.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگوهای تسلیت.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این متن در نحوه نمایش الگو تأثیری نخواهد داشت و تنها برای جستجوی الگو استفاده خواهد شد..
        /// </summary>
        public static string TemplateTextComment {
            get {
                return ResourceManager.GetString("TemplateTextComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ متن.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسیار کوچک.
        /// </summary>
        public static string Tiny {
            get {
                return ResourceManager.GetString("Tiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالا.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبت پهنا به ارتفاع.
        /// </summary>
        public static string WidthHeightRatio {
            get {
                return ResourceManager.GetString("WidthHeightRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شکستن محتوا.
        /// </summary>
        public static string WrapContent {
            get {
                return ResourceManager.GetString("WrapContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
